language: node_js
node_js:
   - "7"
 
branches:
   only:
      - master
      - /^greenkeeper/.*$/

before_script:
   - npm install -g firebase-tools
   - npm install -g @angular/cli

script:
   - npm install
   - ng build --prod --aot

after_success:
   - firebase deploy --token $FIREBASE_TOKEN
