sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
   - "7"
 
branches:
   only:
      - master
      - /^greenkeeper/.*$/

before_script:
   - rm -rf node_modules/
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3
   - npm install -g firebase-tools
   - npm install -g @angular/cli

script:
   - yarn install
   - ng e2e
   #- ng build --prod --aot

#after_success:
#   - firebase deploy --token $FIREBASE_TOKEN
