language: node_js
node_js:
   - "7"
 
branches:
   only:
      - master

before_script:
   - npm install -g firebase-tools
   - npm install -g @angular/cli

script:
   - cd core/
   - ls
   - npm install
   - ng build --prod --aot

after_success:
   - firebase deploy --token "1/-LIF93Mx8FJxJvh-Da7oNnnvw5KEN3afhSRaEJUxQSg"
